### ISSUE TITLE
ASP.NET GRIDVIEW

### ISSUE THREAD

**Issue by afrath123** [chestercharles/excel-bootstrap-table-filter#1]
I AM GENERATING THE TABLE USING ASP.NET BUT SORTING IS NOT WORKING PROPERLY. SORTING WORKING BUT NOT PROPERLY 

<asp:GridView ID="gv" AutoGenerateColumns="false" Width="100%" GridLines="Both"  ClientIDMode="Static"  runat="server"  EmptyDataText="No Data Found!!" 
                                           >
                                            <RowStyle CssClass="GridRow" />
                                            <AlternatingRowStyle CssClass="GridAltRow" />
                                            <HeaderStyle CssClass="GridHeader" />
                                         
                                            <Columns>
                                                <asp:BoundField HeaderText="Client" DataField="PatientName" />
                                                <asp:BoundField HeaderText="Sender" DataField="Sender" />
                                                <asp:BoundField HeaderText="Invoice Number" DataField="Invoice_Number" />
                                                <asp:BoundField HeaderText="Balance" DataField="Balance" />
                                                <asp:BoundField HeaderText="Payor" DataField="PayorName" />
                                                <asp:BoundField HeaderText="Client" DataField="NickName" />
                                                <asp:BoundField HeaderText="Status Reason" DataField="StatusReason" />
                                                 <asp:BoundField HeaderText="HCPC" DataField="HCPC" />
                                            </Columns>
                                        </asp:GridView>

**Comment by afrath123** [comment]
WHICH ALL THE  SCRIPTS NEED TO ADD IN ASPX FILE?  EXACT FILTERING IS WORKING NOT PROPERLY

**Comment by chestercharles** [comment]
The files you need to include from `/dist` are
 - `excel-bootstrap-table-filter-bundle.js`
- `excel-bootstrap-table-filter-style.css`

You will also need to include Bootstrap CSS and JQuery. Here are a couple CDNs:
 - `http://code.jquery.com/jquery-3.2.1.min.js`
 - `https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css`

Does  `/dist/exmaple.html` work properly in your browser?

**Comment by chestercharles** [comment]
#2 might could also be the issue you are having - working on a fix

**Comment by afrath123** [comment]
Any way to edit the column and place a submit button in end of a row? suppose if i change the grid view design to edit mode , the filter is support or not?

**Comment by chestercharles** [comment]
I'm not familiar with ASP.NET gridview - but this plugin only supports HTML tables.

I'm going to close this issue - please use #3 to comment moving forward.
