### ISSUE TITLE
Unable to filter bulk records 

### ISSUE THREAD

**Issue by gundabathula-jatin** [chestercharles/excel-bootstrap-table-filter#10]
Hi,

First of all.. thanks for plugin it really helps for me. but only issue i was facing was if we have 5000+ records in bootstrap table.. the filter is not working as expected once we select any value nothing was rendering and the page was hung up.. any help would be great full...

**Comment by chestercharles** [comment]
Sorry for the late reply @jacksjatin. 

This solution probably does not fit that use case - it is not meant for filtering 1000s of rows. 

I would try to paging your data server-side.
