### ISSUE TITLE
Using with rowspan

### ISSUE THREAD

**Issue by aanair08** [chestercharles/excel-bootstrap-table-filter#12]
Hi, 
Can I use with row span? I tried it with row span but it is not working as I expected. I try with adding hidden td and its working. But When I filter with the second column. row span of the first one is removed. Is there any way to do it properly?

My table is some thing like these. 

          <table id="table" class="table table-bordered table-intel">
                        <thead>
                            <tr>
                                <th class="filter">Animal</th>
                                <th class="filter">Class</th>
                                <th class="filter">Collective Noun</th>
                                <th class="filter">A Number</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td rowspan="4">Bear</td>
                                <td>Mammal</td>
                                <td>Sleuth</td>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td style="display:none">Bear</td>
                                <td>Insect</td>
                                <td>Army</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td style="display:none">Bear</td>
                                <td>Amphibian</td>
                                <td>Congress</td>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td style="display:none">Bear</td>
                                <td>Bird</td>
                                <td>Parliament</td>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td rowspan="3">Frog</td>
                                <td rowspan="3">Amphibian</td>
                                <td>Army</td>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td style="display:none">Frog</td>
                                <td style="display:none">Amphibian</td>
                                <td>Gam</td>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td style="display:none">Frog</td>
                                <td style="display:none">Amphibian</td>
                                <td>Cackle</td>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>Crow</td>
                                <td>Bird</td>
                                <td>Murder</td>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>Elephant</td>
                                <td>Mammal</td>
                                <td>Herd</td>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>Barracude</td>
                                <td>Fish</td>
                                <td>Grist</td>
                                <td>10</td>
                            </tr>
                        </tbody>
                    </table>

**Comment by chestercharles** [comment]
no , sorry using with rowspan is not supported
