### ISSUE TITLE
Dynamic table filtering

### ISSUE THREAD

**Issue by Michaela15a** [chestercharles/excel-bootstrap-table-filter#15]
#Hello, first of all I want to thank you for such a nice plugin that helped me a lot.

I would like to ask you for help. I tried to apply this filter for my dynamically generated table using php and MSSQL but it doesn't work as expected, I get console message.

TypeError: tds[selectedLists[j].column] is undefined.

https://github.com/chestercharles/excel-bootstrap-table-filter/blob/master/dist/excel-bootstrap-table-filter-bundle.js#L274

Thanks a lot for help.

**Comment by chestercharles** [comment]
I'm glad you found the plugin useful!

Sorry for the delay! If you are still trying to use this plugin and having trouble, please create jsfiddle so I can take a look and help debug.

**Comment by Michaela15a** [comment]
Hello,

Thank you for your reply, however I bave foubd another way to solve my
problems.
But great job the excel functionality is very useful.

Michaela

Dňa pi 17. 8. 2018, 22:19 chestercharles <notifications@github.com>
napísal(a):

**Comment by DanAlexson90** [comment]
> Hello,
> 
> Thank you for your reply, however I bave foubd another way to solve my problems. But great job the excel functionality is very useful.
> 
> Michaela

[https://xkcd.com/979/](https://xkcd.com/979/)
