### ISSUE TITLE
Unable to implement in my project

### ISSUE THREAD

**Issue by richa-singh91** [chestercharles/excel-bootstrap-table-filter#17]
I want to implement the same in my project but I don't understand how to import the plugin.
Please guide me

**Comment by chestercharles** [comment]
Hi there - the usage directions in the README should be pretty straightforward. 

Take a look in the `dist` folder. There are two files you need:
- `checkbox-dropdown-plugin.min.js` 
- `checkbox-dropdown-style.css`

Make sure these files are imported into your project.

You will also need to import the bootstrap library into your project. Take a look at their website if you arent sure how to do that.
