### ISSUE TITLE
Please, explain how to access the filter state

### ISSUE THREAD

**Issue by git-hub-user** [chestercharles/excel-bootstrap-table-filter#18]
We are using the filter plug-in to allow users to deselect rows in a data set. I am refactoring the code, as a previous developer had made changes to the plug-in, which I want to leave unchanged, to be able to upgrade to newer version, without the need to reapply those changes.

I managed to do this for many changes and the UI works quite well again, but now I want to access the filter state, to apply it to the original data set. That is, when the user is done filtering values and ready to save the state, I want to know which values have been deselected for each column.

I have been looking at `FilterCollection.prototype.updateRowVisibility` and the local var `selectedLists`, which seems useful, but is not accessible.

So, I would like to have access to a data structure that tells me for each column which values have been selected and/or deselected.

For now, I think my best option is to duplicate the code that sets the local var `selectedLists`, or is there a better way?

**Comment by chestercharles** [comment]
Unfortunately, I didn't really design with state-saving in mind. 

However, you could modify the code to make `selectedLists` a public member of the `FilterCollection` instead of a local variable in the `updateRowVisibility` method.

**Comment by amrjoja** [comment]
Hi @chestercharles, I need some help with this function `FilterCollecti/on.prototype.updateRowVisibility`.

The current behavior:
the checkboxes in filtering have **checked** that means all rows are **showing**, and when unchecked for any attribute in filtering will hide the rows that associated with it.

what I want to do is:
The checkboxes in filtering have **Unchecked** and all rows are **showing**, then when checked for any attribute in filtering will hide all rows without the rows that associated with this attribute(just showing the rows that associated with this attribute).

I am sorry for the weakness of my language

**Comment by chestercharles** [comment]
Hi @amrjoja, your language is fine 👍 

However, the the requested behavior seems counterintuitive to the way checkboxes should work. I do not think it is worth the effort to add this to the library. Sorry!
