### ISSUE TITLE
should not sort numbers like strings

### ISSUE THREAD

**Issue by chestercharles** [chestercharles/excel-bootstrap-table-filter#2]

**Comment by afrath123** [comment]
Instead of html table is it possible to filtering work on asp.net grid view control

**Comment by chestercharles** [comment]
sorry the scope of this project was just to work on HTML tables - I'm not familiar with asp.net grid view control

**Comment by chestercharles** [comment]
commit a96ab0d59f03297fd449924bd854da7c3b284935 fixes the number sort issue
