### ISSUE TITLE
[Pagination]

### ISSUE THREAD

**Issue by Patryck97** [chestercharles/excel-bootstrap-table-filter#23]
Hi,
I am using your filter and I realised that having a table that uses pagination, your filter only gives me as options in the filter, the values that are in the first page of the pagination. The search/filters also only apply to the first page.

Is there any way around this? 

Thanks,
Patryck

**Comment by chestercharles** [comment]
Hi Patryck. If your pagination is server side, then it will not work. The list of values to filter/search by are built by inspecting the content in the DOM.

**Comment by Patryck97** [comment]
Ok, that explains it. Thanks.
