### ISSUE TITLE
Header filter dropdown hide

### ISSUE THREAD

**Issue by afrath123** [chestercharles/excel-bootstrap-table-filter#3]
Any settings to hide a single column filter or multiple column filter. if no,

2. any way to provide checkbox on first column for selecting all and selecting individual for another purpose?

**Comment by chestercharles** [comment]
> Any settings to hide a single column filter or multiple column filter

do you mean you want to be able to hide this section?

![image](https://user-images.githubusercontent.com/8016126/29197526-e26286a0-7df0-11e7-98a2-612436c850f4.png)

**Comment by chestercharles** [comment]
> any way to provide checkbox on first column for selecting all and selecting individual for another purpose?

Not 100% sure what you mean ... do you want a clear all filters button?

**Comment by afrath123** [comment]
![capture](https://user-images.githubusercontent.com/30865901/29200628-8bfb8602-7e74-11e7-8f85-d617155ef48b.PNG)
I need the checkbox in front of the table to select the all data or individually? is it possible?

**Comment by afrath123** [comment]
now if i add a checkbox in front , it displaying but  we apply the filter  , result won't come

**Comment by chestercharles** [comment]
Can you create fiddle that shows the issue that you are having?

See here for a working example: https://jsfiddle.net/chestercharles/knwthx4m/

**Comment by afrath123** [comment]
https://jsfiddle.net/zhzmLtho/1/

please reefer the fiddle . 
1. in the first column checkbox is there in that particular column we don't need filtering option.
2. we need to edit the column values or we need drop down in  any of the column.
3. add a save button on end of the row and if we click it will save

the above requirements are
is it possible?

**Comment by afrath123** [comment]
i took the latest version of excel-bootstrap-table-filter-bundle.js from your code, but the filter is come initially, once  we applied a filter the header filter row is hide. when i  inspect element in the browser the header row is added a class display none after your new update.

**Comment by chestercharles** [comment]
> 1. in the first column checkbox is there in that particular column we don't need filtering option.

You can disable filtering options by using`columnSelector` in the config. 

    $('#table').excelTableFilter({
        columnSelector: '.apply-filter',    // if present, will only select <th> with specified class
    });

> 2. we need to edit the column values or we need drop down in any of the column.

This will not work - the filter searches the` innerText` of `<td>` elements to determine what to filter. Any HTML content within the `<td>` will be ignored.

> 3. add a save button on end of the row and if we click it will save

Saving the filter configuration? If so, sounds like a cool idea, but I will not be able to implement this anytime soon - feel free to make a pull request.

**Comment by afrath123** [comment]
Update the new code excel-bootstrap-table-filter-bundle.js and apply in the our project but once we apply the filter the header section automatically hide. if we inspect  element  header tr attaching   display: none; .

**Comment by chestercharles** [comment]
**It sounds like you may not be using `<thead>` and `<tbody>` elements.**

The plugin relies on those semantic elements to know what is in the header and what is in the table body.

Are getting the behavior shown in [this fiddle](https://jsfiddle.net/chestercharles/fks454su/) ? If so, that is likely the culprit.
