### ISSUE TITLE
Question: Default filter on page load

### ISSUE THREAD

**Issue by brmenezewe** [chestercharles/excel-bootstrap-table-filter#34]
Hi, first of all great job!

I have table which I applied your plug in and I would like to know if I can fitler a value by default and unfilter it manually rather than the other way around. So, Is it possible to call a function in my own js file to apply a default filter on page load?

**Comment by git-hub-user** [comment]
I have achieved this by finding the applicable checkboxes in the column headers and cliking them to uncheck. 

```
// filter by zero-based column index and value.
function filter(filterColumn, filterValue) {
  tableWithFilter.find('th .checkbox-container > .dropdown-filter-item > input.dropdown-filter-menu-item.item[data-column="' + filterColumn + '"][value="' + filterValue + '"]').each(
    function() {
      if ($(this).prop('checked')) {
        $(this).click();
      }
    });
}
```

See [JsFiddle](https://jsfiddle.net/RSchreurs/j4rof8g6/).

There is one issue in the fiddle: for each column I apply a filter to, the filter with checkboxes becomes invisible. This is not the case in my own solution. Could be a result of missing styles, the use of jsFiddle or the bit of refactoring I needed to apply.
Anyway, I think the solution is clearly demonstrated.

**Comment by brmenezewe** [comment]
Thanks a lot @git-hub-user! I managed to adapt your function to my need and it works fine. For future reference it looks like this:

```
// filter by zero-based column index and value.
function EXCEL_LIKE_DEFAULT_FILTER(table_id, column_index, default_filter_value) {
    $('#' + table_id).find('th .checkbox-container > .dropdown-filter-item > input.dropdown-filter-menu-item.item[data-column="' + column_index + '"]').each(function() {
        if ( $(this).prop('checked') && $(this).val() != default_filter_value) {
          $(this).click();
        }
      });
  }
```
