### ISSUE TITLE
filtering issue

### ISSUE THREAD

**Issue by afrath123** [chestercharles/excel-bootstrap-table-filter#4]
When i try to filter the grid column, it shows wrong result set.
For eg: I have three columns with contains **Customer Names, Address and Balance amount**

Issue 1: when i try to select Single / Multiple ( Customer Names / Address / Balance ), it shows wrong result set. Same case i try for multi column filter. The result set is completely wrong.

Issue 2: When i  added checkbox in the first column, the filter is not working.

If i try to add item template in the Grid view, filter  will work or not.?

Please help me in the above issue.

**Comment by chestercharles** [comment]
commit a96ab0d59f03297fd449924bd854da7c3b284935 fixed a lot of bugs that may have been causing some issues. let me know if you are still having the same issues

**Comment by chestercharles** [comment]
closing this issue, please use #3 moving forward
