### ISSUE TITLE
Sticky-header (floatThead) is not rendering correctly

### ISSUE THREAD

**Issue by yozart** [chestercharles/excel-bootstrap-table-filter#45]
When having a floatThead on a table, filters are only showing when we are at the top of the page.

If you scroll down and try to filter, this won't show. Example here :

https://jsfiddle.net/9713qa6n/

**Comment by mkoryak** [comment]
This is not this filter's fault, they cannot be expected to handle what other plugins do to the DOM. 

Here is an ugly hack that solves your problem:
https://jsfiddle.net/08hf4pdt/

It also voids the warranty on the flaotthead plugin, but I doubt you care :)

**Comment by yozart** [comment]
Wow great ! thank you very much for your help

**Comment by yozart** [comment]
This fix works for me !
