### ISSUE TITLE
Possible to have two tables on same page?

### ISSUE THREAD

**Issue by Rioxales** [chestercharles/excel-bootstrap-table-filter#5]
I have two separate tables in a view and would like both tables to have the Excel filter options.

Currently, the filters do appear on both tables, but the filter options are combined when I'd like them to be separated out. The filter options work with the first table, but if I unselect and select an option in the second table, the entire table disappears and doesn't reappear.

![image](https://user-images.githubusercontent.com/31012000/29280459-ea6eeb2a-80e0-11e7-8aec-3e3ddd8e95c4.png)

Is there a simple way to adjust the script two create two separate filter collections without refactoring much?

**Comment by chestercharles** [comment]
@Rioxales - I think this commit should fix that issue. Definitely reasonable to expect that the script should support multiple tables on the same page :)

**Comment by chestercharles** [comment]
working example: https://jsfiddle.net/chestercharles/m16eeky0/

**Comment by chestercharles** [comment]
actual commit was b39bd3d0a41a09e00c80b6302e533f96b2eec089
