### ISSUE TITLE
line vanishes after filtering and then removing the filter

### ISSUE THREAD

**Issue by jayjayeos** [chestercharles/excel-bootstrap-table-filter#7]
The first line in the table vanishes after applying and removing a (actually any) filter.

**Comment by chestercharles** [comment]
Can you provide more details on how to duplicate this behavior?

I'm unable to duplicate your issue in Chome 61 or IE11 using this fiddle: https://jsfiddle.net/chestercharles/20tz86gy/1/

**Comment by jayjayeos** [comment]
Issue happens if TDs contain other tags like BR. I'm guessing child enumeration of the TRs gets confused.

**Comment by chestercharles** [comment]
Latest commit should resolve the issue:
https://jsfiddle.net/chestercharles/fkpz2avh/1/

**Comment by jayjayeos** [comment]
Also tables with COLSPANs aren't handled correctly.

**Comment by chestercharles** [comment]
what incorrect behavior are you observing?

it appears to work fine in this example:
https://jsfiddle.net/chestercharles/6qjeecwo/3/
